name: Update Badges

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches: [main]

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Create badge JSON files
      run: |
        mkdir -p .github/badges

        # Coverage badge (placeholder - will be updated by CI)
        echo '{"schemaVersion": 1, "label": "coverage", "message": "90%+", "color": "brightgreen"}' > .github/badges/coverage.json

        # Tests badge
        echo '{"schemaVersion": 1, "label": "tests", "message": "passing", "color": "brightgreen"}' > .github/badges/tests.json

        # Python version badge
        echo '{"schemaVersion": 1, "label": "python", "message": "3.13+", "color": "blue"}' > .github/badges/python.json
